-- Add deterministic structured before/after evidence and include it in a v3
-- tenant hash chain. Text contains canonical JSON generated by the application;
-- using the exact stored bytes keeps external verification unambiguous.
ALTER TABLE "AuditLog" NO FORCE ROW LEVEL SECURITY;

ALTER TABLE "AuditLog"
  ADD COLUMN "outcome" TEXT NOT NULL DEFAULT 'SUCCESS',
  ADD COLUMN "reason" TEXT,
  ADD COLUMN "beforeState" TEXT,
  ADD COLUMN "afterState" TEXT;

ALTER TABLE "AuditLog"
  ADD CONSTRAINT "AuditLog_outcome_check" CHECK ("outcome" IN ('SUCCESS', 'FAILURE', 'DENIED')),
  ADD CONSTRAINT "AuditLog_reason_length_check" CHECK ("reason" IS NULL OR length("reason") <= 2000),
  ADD CONSTRAINT "AuditLog_beforeState_length_check" CHECK ("beforeState" IS NULL OR octet_length("beforeState") <= 32000),
  ADD CONSTRAINT "AuditLog_afterState_length_check" CHECK ("afterState" IS NULL OR octet_length("afterState") <= 32000);

CREATE OR REPLACE FUNCTION hoterra_audit_hash_v3(
  audit_id TEXT,
  audit_tenant_id TEXT,
  audit_user_id TEXT,
  audit_user_name TEXT,
  audit_action TEXT,
  audit_entity_type TEXT,
  audit_entity_id TEXT,
  audit_details TEXT,
  audit_ip_address TEXT,
  audit_device TEXT,
  audit_request_id TEXT,
  audit_outcome TEXT,
  audit_reason TEXT,
  audit_before_state TEXT,
  audit_after_state TEXT,
  audit_created_at TIMESTAMP(3),
  audit_sequence INTEGER,
  audit_previous_hash TEXT
) RETURNS TEXT
LANGUAGE SQL
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT encode(
    digest(
      concat_ws(E'\x1f',
        COALESCE(audit_id, ''),
        COALESCE(audit_tenant_id, ''),
        COALESCE(audit_user_id, ''),
        COALESCE(audit_user_name, ''),
        COALESCE(audit_action, ''),
        COALESCE(audit_entity_type, ''),
        COALESCE(audit_entity_id, ''),
        COALESCE(audit_details, ''),
        COALESCE(audit_ip_address, ''),
        COALESCE(audit_device, ''),
        COALESCE(audit_request_id, ''),
        COALESCE(audit_outcome, ''),
        COALESCE(audit_reason, ''),
        COALESCE(audit_before_state, ''),
        COALESCE(audit_after_state, ''),
        to_char(audit_created_at, 'YYYY-MM-DD"T"HH24:MI:SS.MS'),
        COALESCE(audit_sequence::TEXT, ''),
        COALESCE(audit_previous_hash, '')
      ),
      'sha256'
    ),
    'hex'
  );
$$;

DO $$
DECLARE
  tenant_row RECORD;
  audit_row RECORD;
  previous_hash TEXT;
  calculated_hash TEXT;
BEGIN
  FOR tenant_row IN SELECT "id" FROM "Tenant" ORDER BY "id" LOOP
    previous_hash := '';
    FOR audit_row IN
      SELECT * FROM "AuditLog"
      WHERE "tenantId" = tenant_row."id"
      ORDER BY "sequence"
    LOOP
      calculated_hash := hoterra_audit_hash_v3(
        audit_row."id", audit_row."tenantId", audit_row."userId", audit_row."userName",
        audit_row."action"::TEXT, audit_row."entityType", audit_row."entityId", audit_row."details",
        audit_row."ipAddress", audit_row."device", audit_row."requestId", audit_row."outcome",
        audit_row."reason", audit_row."beforeState", audit_row."afterState", audit_row."createdAt",
        audit_row."sequence", previous_hash
      );
      UPDATE "AuditLog"
      SET "previousHash" = previous_hash,
          "entryHash" = calculated_hash
      WHERE "id" = audit_row."id";
      previous_hash := calculated_hash;
    END LOOP;
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION hoterra_chain_audit_insert()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  last_sequence INTEGER;
  last_hash TEXT;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(NEW."tenantId", 1700));
  SELECT "sequence", "entryHash"
    INTO last_sequence, last_hash
    FROM "AuditLog"
    WHERE "tenantId" = NEW."tenantId"
    ORDER BY "sequence" DESC
    LIMIT 1;

  NEW."sequence" := COALESCE(last_sequence, 0) + 1;
  NEW."previousHash" := COALESCE(last_hash, '');
  NEW."entryHash" := hoterra_audit_hash_v3(
    NEW."id", NEW."tenantId", NEW."userId", NEW."userName", NEW."action"::TEXT,
    NEW."entityType", NEW."entityId", NEW."details", NEW."ipAddress", NEW."device",
    NEW."requestId", NEW."outcome", NEW."reason", NEW."beforeState", NEW."afterState",
    NEW."createdAt", NEW."sequence", NEW."previousHash"
  );
  RETURN NEW;
END $$;

ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
