export const CAPABILITIES = [
  'dashboard.view',
  'documents.read',
  'documents.read.all',
  'documents.create',
  'documents.update',
  'documents.delete',
  'documents.export',
  'documents.archive',
  'documents.restore',
  'records.manage',
  'records.disposition.request',
  'records.disposition.approve',
  'documents.approve',
  'documents.sign',
  'approvals.read',
  'templates.read',
  'templates.manage',
  'departments.read',
  'departments.manage',
  'workflows.read',
  'workflows.manage',
  'users.directory.read',
  'users.create',
  'users.update',
  'users.deactivate',
  'users.password.reset',
  'roles.read',
  'roles.manage',
  'roles.assign.privileged',
  'workforce.read',
  'workforce.request.create',
  'workforce.templates.manage',
  'workforce.vendor.manage',
  'workforce.routes.manage',
  'workforce.reports.read',
  'workforce.reports.export',
  'workforce.settings.manage',
  'workforce.budget.manage',
  'workforce.invoice.manage',
  'reports.read',
  'reports.export',
  'audit.read',
  'audit.export',
  'settings.read',
  'settings.manage.business',
  'settings.manage.security',
  'notifications.read',
  'search.use',
  'messages.use',
] as const;

export type Capability = (typeof CAPABILITIES)[number];

export function isCapability(value: string): value is Capability {
  return (CAPABILITIES as readonly string[]).includes(value);
}
